.PHONY: clean All

All:
	@echo "----------Building project:[ ExtendVector - Debug ]----------"
	@cd "ExtendVector" && "$(MAKE)" -f  "ExtendVector.mk"
clean:
	@echo "----------Cleaning project:[ ExtendVector - Debug ]----------"
	@cd "ExtendVector" && "$(MAKE)" -f  "ExtendVector.mk" clean
